# install.packages("e1071")
# library(e1071)
# s = svm(Species~., data = iris)
# print(s)
# table(predict(s, iris), iris$Species)
# s = svm(Species~., data=iris, kernel='polynomial')
# table(predict(s, iris), iris$Species)
s = svm(Species~., data=iris, cost=100)
p = predict(s, iris)
table(p, iris$Species)
